language: node_js

node_js:
  - 4
  - 6
  - 8
  - node # Latest

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: deploy
      script: skip
      node_js: 8 # semantic-release requires Node >= 8.3
      # NOTE: Pull Request builds do not run deploy
      deploy:
        provider: script
        on:
          branch: master
        skip_cleanup: true
        script:
          # - npm run security-scan
          - npm run release

cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change