language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "node"

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: deploy
      script: skip
      # NOTE: Pull Request builds do not run deploy
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release

cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change